language: python
python:
  - "3.5"
install:
  - pip install -r requirements_for_test.txt
script:
  - ONS_ENV=test pytest --cov=swagger_server/controllers_local
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
    slack: surveydatacollection:LCbNJJpDoY3gYIvLOlK0nZkV
